#!/bin/sh
#
# @name Rematrice Quadcopter (27 inch, 12S Li-ion, provisional 15.175kg)
#
# @type Quadrotor x
# @class Copter
#
# @maintainer User
#

. ${R}etc/init.d/rc.mc_defaults

# Load default params for this platform
param set-default CA_ROTOR_COUNT 4
param set-default CA_AIRFRAME 0

# CAD-derived rotor centers relative to estimated loaded CG, PX4 FRD.
# Full axes include the CAD motor cant. See validation/cad_model.json.

# Motor 0: CCW
param set-default CA_ROTOR0_PX 0.3620587992
param set-default CA_ROTOR0_PY 0.4593365464
param set-default CA_ROTOR0_PZ -0.0723684018
param set-default CA_ROTOR0_AX 0.0000000000
param set-default CA_ROTOR0_AY -0.0906019298
param set-default CA_ROTOR0_AZ -0.9958871875
param set-default CA_ROTOR0_KM 0.030258354

# Motor 1: CCW
param set-default CA_ROTOR1_PX -0.4334280408
param set-default CA_ROTOR1_PY -0.4504128060
param set-default CA_ROTOR1_PZ 0.0034928121
param set-default CA_ROTOR1_AX 0.0000000000
param set-default CA_ROTOR1_AY -0.1475170132
param set-default CA_ROTOR1_AZ -0.9890595183
param set-default CA_ROTOR1_KM 0.030258354

# Motor 2: CW
param set-default CA_ROTOR2_PX 0.3620587992
param set-default CA_ROTOR2_PY -0.4561008257
param set-default CA_ROTOR2_PZ -0.0723684018
param set-default CA_ROTOR2_AX 0.0000000000
param set-default CA_ROTOR2_AY 0.0906019352
param set-default CA_ROTOR2_AZ -0.9958871871
param set-default CA_ROTOR2_KM -0.030258354

# Motor 3: CW
param set-default CA_ROTOR3_PX -0.4334280408
param set-default CA_ROTOR3_PY 0.4536485006
param set-default CA_ROTOR3_PZ 0.0034928120
param set-default CA_ROTOR3_AX 0.0000000000
param set-default CA_ROTOR3_AY 0.1475170305
param set-default CA_ROTOR3_AZ -0.9890595158
param set-default CA_ROTOR3_KM -0.030258354

# Output Mapping
param set PWM_MAIN_FUNC1 101
param set PWM_MAIN_FUNC2 102
param set PWM_MAIN_FUNC3 103
param set PWM_MAIN_FUNC4 104

# pwm_out_sim uses normalized motor outputs. PWM_MAIN_MIN/MAX do not
# exist in this SITL build; physical FLAME PWM endpoints are not emulated.

# Pure quadratic Gazebo thrust law; MAVLink scaling is 397.306751 rad/s,
# zero armed offset. PX4 applies sqrt(thrust) with this setting.
param set-default THR_MDL_FAC 1.0
# Mean motor fraction from CAD force/moment equilibrium at 15.17464kg.
param set-default MPC_THR_HOVER 0.4622686272

# User-confirmed 12S 22Ah Li-ion. Voltages are provisional conventional
# 4.2V/cell Li-ion settings; verify cell chemistry, BMS and loaded cutoff.
param set-default BAT1_N_CELLS 12
param set-default BAT1_CAPACITY 22000
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_EMPTY 3.0

# PX4's stock battery simulator is a TIME-based proxy (no current, sag,
# temperature or motor-voltage coupling). ~22Ah/33A = 2400s full discharge
# at a constant bench-hover load, NOT a validated flight-time prediction.
param set-default SIM_BAT_ENABLE 1
param set-default SIM_BAT_DRAIN 2400
param set-default SIM_BAT_MIN_PCT 0

# Headless offboard: land when the setpoint stream stops (COM_OF_LOSS_T).
param set-default COM_OBL_RC_ACT 4

# Simulated sensor lever arms relative to model CG (FRD).
param set-default EKF2_IMU_POS_X 0.0712611617
param set-default EKF2_IMU_POS_Y 0.0008632283
param set-default EKF2_IMU_POS_Z -0.1302616604
param set-default EKF2_GPS_POS_X -0.1062724661
param set-default EKF2_GPS_POS_Y 0.0011350401
param set-default EKF2_GPS_POS_Z 0.0116696553
